/**
 * makeVercelEntry.mjs — emit the Vercel output directory.
 *
 * THREE platform constraints, each learned from a build or runtime log rather
 * than assumed, all satisfied by what this script emits:
 *
 * 1. The Node/Express preset picks a server entrypoint BY FILENAME from the
 *    output directory (`app.*`, `index.*`, `server.*`, `src/*`). Pointing it at
 *    `dist/` made our own `src/server.ts` -> `dist/server.js` a candidate — the
 *    MCP wiring module, which exports `createApp` and no app — and it won:
 *      Invalid export found in module "/var/task/dist/server.js".
 *    So this directory holds exactly ONE candidate.
 *
 * 2. That candidate must IMPORT EXPRESS DIRECTLY. A bare re-export failed with:
 *      No entrypoint found which imports express. Found possible entrypoint: index.js
 *    So the entry is a real outer express app, and it earns the import:
 *    `trust proxy` is genuinely required because Vercel terminates TLS upstream,
 *    and without it `req.protocol`/`req.ip` report the proxy hop rather than the
 *    client — dishonest values, on this server in particular.
 *
 * 3. `fixture.json` and `dial.json` are read at RUNTIME with `readFileSync`, so
 *    Vercel's static tracer cannot see them and did not ship them:
 *      [honestbench] fixture.json + dial.json not found in any of: /var/task | …
 *    They are therefore COPIED next to the entry here, and the entry tells the
 *    app where they are via HONESTBENCH_ROOT. They are copied as BYTES, never
 *    re-serialised — the sha256 that identifies a run is a property of the file,
 *    and a reformat would silently change the run's identity.
 *
 * `src/index.ts`, `src/server.ts` and the Dockerfile are untouched throughout.
 */
import { copyFileSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { createHash } from 'node:crypto';

const DIR = 'vercel-build';
const ENTRY = `${DIR}/index.js`;
const DATA_FILES = ['fixture.json', 'dial.json'];

const SOURCE = `// GENERATED by scripts/makeVercelEntry.mjs — do not edit.
//
// The ONLY entrypoint candidate in this directory, so Vercel's preset cannot
// select one of the instrument's own modules by name. It imports express
// directly because the preset requires the entrypoint to do so.
import express from 'express';
import { fileURLToPath } from 'node:url';
import { dirname } from 'node:path';

// fixture.json + dial.json are copied HERE at build time (Vercel's tracer cannot
// see a runtime readFileSync). Point the app at this directory BEFORE loading
// it — hence the dynamic import: a static one is hoisted above this assignment.
process.env.HONESTBENCH_ROOT = dirname(fileURLToPath(import.meta.url));

const { default: inner } = await import('../dist/app.js');

const app = express();

// Vercel terminates TLS upstream. Without this, req.protocol and req.ip report
// the proxy hop rather than the client — dishonest values on a server whose
// entire purpose is measuring honesty.
app.set('trust proxy', true);

app.use(inner);

export default app;
`;

mkdirSync(DIR, { recursive: true });
writeFileSync(ENTRY, SOURCE, 'utf8');

for (const f of DATA_FILES) {
    copyFileSync(f, `${DIR}/${f}`);
    const src = createHash('sha256').update(readFileSync(f)).digest('hex');
    const dst = createHash('sha256').update(readFileSync(`${DIR}/${f}`)).digest('hex');
    // The copy must be byte-identical or the deployed run is not the run whose
    // hash the report cites. Checked rather than trusted.
    if (src !== dst) throw new Error(`${f}: copy is not byte-identical (${src} != ${dst})`);
    console.log(`[honestbench] copied ${f} -> ${DIR}/${f}  sha256 ${src}`);
}

console.log(`[honestbench] wrote ${ENTRY} (outer express app -> ../dist/app.js)`);
