/**
 * makeVercelEntry.mjs — emit the Vercel output directory.
 *
 * TWO platform constraints, both learned from build/runtime logs rather than
 * assumed, and both satisfied by this one generated file:
 *
 * 1. The Node/Express preset picks a server entrypoint BY FILENAME from the
 *    output directory (`app.*`, `index.*`, `server.*`, `src/*`). Pointing it at
 *    `dist/` made our own `src/server.ts` -> `dist/server.js` a candidate — the
 *    MCP wiring module, which exports `createApp` and no app — and it was
 *    selected:
 *      Invalid export found in module "/var/task/dist/server.js".
 *    So the output directory here holds exactly ONE candidate.
 *
 * 2. That candidate must IMPORT EXPRESS DIRECTLY. A bare re-export failed with:
 *      No entrypoint found which imports express. Found possible entrypoint: index.js
 *    So the entry is a real outer express app rather than a pass-through, and it
 *    earns the import: `trust proxy` is genuinely needed because Vercel
 *    terminates TLS upstream, so without it `req.protocol` and `req.ip` lie —
 *    which would be a poor look on this server in particular.
 *
 * Renaming our own module would have edited `src/index.ts`, which the GO
 * requires to stay byte-unchanged. `src/index.ts`, `src/server.ts` and the
 * Dockerfile are all untouched.
 */
import { mkdirSync, writeFileSync } from 'node:fs';

const DIR = 'vercel-build';
const ENTRY = `${DIR}/index.js`;

const SOURCE = `// GENERATED by scripts/makeVercelEntry.mjs — do not edit.
//
// The ONLY entrypoint candidate in this directory, so Vercel's preset cannot
// select one of the instrument's own modules by name. It imports express
// directly because the preset requires the entrypoint to do so.
import express from 'express';
import inner from '../dist/app.js';

const app = express();

// Vercel terminates TLS upstream. Without this, req.protocol and req.ip report
// the proxy hop rather than the client — dishonest values on a server whose
// entire purpose is measuring honesty.
app.set('trust proxy', true);

app.use(inner);

export default app;
`;

mkdirSync(DIR, { recursive: true });
writeFileSync(ENTRY, SOURCE, 'utf8');

console.log(`[honestbench] wrote ${ENTRY} (outer express app -> ../dist/app.js)`);
